// src/components/OTPInput.tsx
import React, { FunctionComponent } from 'react'

import styles from './OTPInput.module.css'

type OTPInputProps = {
    // the number of inputs fields to render
    // and also the length of the passcode to generate
    length: number
}

const OTPInput: FunctionComponent<OTPInputProps> = ({length}) => {
    return <div className={styles['OTPInput']}>
        Create {length} inputs here
    </div>
}

export default OTPInput

// solid-js/src/components/OTPInput.tsx
import { Component, splitProps } from "solid-js";

type OTPInputProps = {
  // the number of inputs fields to render
  // and also the length of the passcode to generate
  length: number;
};

const OTPInput: Component<OTPInputProps> = (props) => {
  const [{ length }] = splitProps(props, ["length"]);

  return (
    <>
      <div class={"inline-block p-4 border space-x-1"}>
        Create {length} inputs here.
      </div>
      <pre class="font-mono text-gray-500 pt-2"></pre>
    </>
  );
};

export default OTPInput;
